apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sql-server-network-policy
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: backend
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: log-policy
spec:
  podSelector:
    matchLabels:
      role: log
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
          - {key: role, operator: In, values: [backend, frontend]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: theidserver-private-policy
spec:
  podSelector:
    matchLabels:
      role: backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend
            