apiVersion: v1
kind: ConfigMap
metadata:
  name: public-config
  namespace: theidserver
data:
  ASPNETCORE_ENVIRONMENT: Docker
  ASPNETCORE_Kestrel__Certificates__Default__Path: /usr/local/share/ca-certificates/tls-public.pfx
  ASPNETCORE_URLS: https://+:80;https://+:443
  ASPNETCORE_HTTPS_PORT: "443"
  Proxy: "true"
  DisableStrictSsl: "true"
  EnableOpenApiDoc: "false"
  IdentityServer__Key__Type: KeysRotation
  IdentityServer__Key__StorageKind: FileSytem
  IdentityServer__Key__StorageConnectionString: "/usr/local/share/keys/signing"
  IdentityServer__Key__KeyProtectionOptions__KeyProtectionKind: "X509"
  IdentityServer__Key__KeyProtectionOptions__X509CertificatePath: /usr/local/share/ca-certificates/theidserver.pfx
  DataProtectionOptions__StorageKind: FileSytem
  DataProtectionOptions__StorageConnectionString: "/usr/local/share/keys/dataprotecttion"
  DataProtectionOptions__KeyProtectionOptions__KeyProtectionKind: "X509"
  DataProtectionOptions__KeyProtectionOptions__X509CertificatePath: /usr/local/share/ca-certificates/theidserver.pfx
  ApiAuthentication__Authority: https://localhost
  ApiAuthentication__IntrospectionDiscoveryPolicy__ValidateIssuerName: "false"
  PrivateServerAuthentication__Authority: "https://theidserver-private:5443"
  PrivateServerAuthentication__ApiUrl: "https://theidserver-private:5443/api"
  EmailApiAuthentication__Authority: https://localhost
  EmailApiAuthentication__ApiUrl: https://localhost/api/email
  SignalR__HubOptions__EnableDetailedErrors: "true"
  SignalR__UseMessagePack: "true"
  SignalR__HubUrl: https://theidserver-private:5443/providerhub
  SignalR__RedisOptions__Configuration__ChannelPrefix: TheIdServer
  Serilog__WriteTo__0__Args__serverUrl: http://seq:5341
  Serilog__WriteTo__0__Args__apiKey: MYZxOmhzGAwCtEyqLsQS
