apiVersion: v1
kind: ConfigMap
metadata:
  name: private-config
  namespace: theidserver
data:
  ASPNETCORE_ENVIRONMENT: Docker
  ASPNETCORE_Kestrel__Certificates__Default__Path: /usr/local/share/ca-certificates/tls-private.pfx
  ASPNETCORE_URLS: https://+:5443
  ASPNETCORE_HTTPS_PORT: "5443"
  DisableStrictSsl: "true"
  EnableOpenApiDoc: "false"
  IdentityServer__Key__Type: "KeysRotation"
  IdentityServer__Key__StorageKind: "Redis"
  IdentityServer__Key__StorageConnectionString: "redis:6379"
  IdentityServer__Key__KeyProtectionOptions__KeyProtectionKind: "X509"
  IdentityServer__Key__KeyProtectionOptions__X509CertificatePath: /usr/local/share/ca-certificates/theidserver.pfx
  DataProtectionOptions__StorageKind: "Redis"
  DataProtectionOptions__StorageConnectionString: "redis:6379"
  DataProtectionOptions__KeyProtectionOptions__KeyProtectionKind: "X509"
  DataProtectionOptions__KeyProtectionOptions__X509CertificatePath: /usr/local/share/ca-certificates/theidserver.pfx
  ApiAuthentication__Authority: https://localhost:5443
  ApiAuthentication__IntrospectionDiscoveryPolicy__ValidateIssuerName: "false"
  EmailApiAuthentication__Authority: https://localhost:5443
  EmailApiAuthentication__ApiUrl: https://localhost:5443/api/email
  SignalR__HubOptions__EnableDetailedErrors: "true"
  SignalR__UseMessagePack: "true"
  SignalR__RedisConnectionString: "redis:6379"
  SignalR__HubUrl: https://theidserver-private:5443/providerhub
  SignalR__RedisOptions__Configuration__ChannelPrefix: TheIdServer
  Serilog__WriteTo__0__Args__serverUrl: http://seq:5341
  Serilog__WriteTo__0__Args__apiKey: T9OBdJpuMS4nsRgTRzaP
