apiVersion: v1
kind: Service
metadata:
  name: theidserver-public
  namespace: theidserver
  labels:
    run: theidserver-public
spec:
  selector:
    app: theidserver-public
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
